import {
  LayoutDashboard,
  BookOpen,
  Compass,
  Mic,
  Tag,
  BarChart2,
  FileText,
  Calendar,
  Plus,
  Search,
  ChevronRight,
  ChevronDown,
  Check,
  X,
  Copy,
  MessageSquare,
  Sparkles,
  Clock,
  Pin,
  Filter,
  SortAsc,
  Download,
  Upload,
  Trash2,
  Edit2,
  ExternalLink,
  AlertCircle,
  CheckCircle,
  Info,
  Settings,
  MoreVertical,
  Eye,
  EyeOff,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  sources: BookOpen,
  discover: Compass,
  interviews: Mic,
  themes: Tag,
  data: BarChart2,
  drafts: FileText,
  planning: Calendar,
  settings: Settings,
  add: Plus,
  search: Search,
  next: ChevronRight,
  expand: ChevronDown,
  check: Check,
  close: X,
  copy: Copy,
  comment: MessageSquare,
  ai: Sparkles,
  clock: Clock,
  pin: Pin,
  filter: Filter,
  sort: SortAsc,
  download: Download,
  upload: Upload,
  delete: Trash2,
  edit: Edit2,
  external: ExternalLink,
  error: AlertCircle,
  success: CheckCircle,
  info: Info,
  more: MoreVertical,
  view: Eye,
  hide: EyeOff,
};
